export default {
  ADD_TASK: 'ADD_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  SET_TASK_LIST: 'SET_TASK_LIST',
  SET_ERROR: 'SET_ERROR',
  SELECT_TASK: 'SELECT_TASK',
  SELECT_FOLDER: 'SELECT_FOLDER'
}
